version: '3.3'
services:
  stove-bridge:
    image: registry.sensou.de:443/d.wyschka/stove-bridge:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stove-bridge
    restart: always
    environment:
      HSP_STOVE_IP: "10.10.48.134"
      HSP_STOVE_PIN: 2749
      MQTT_IP: "10.10.48.34"
      HSP_POLL_INTERVAL: 15
      MQTT_PORT: 1883
